#' Manhattan plot beautifier adapted from GWASpoly::manhattan.plot customized
#'
#' @param data,traits,models,chrom See GWASpoly::manhattan.plot documentation
#' @param chrom_color          : vec(str, str)  List of 2 string color for
#'                                              alternate coloration of marker.
#' @param significant_color    : str            String color for significant
#'                                              marker, NULL  leaves significant
#'                                              markers with the same color as
#'                                              not significant ones.
#' @param point_size           : float          Diameter of the points.
#' @param point_alpha          : float          Points transparency.
#' @param threshold_line_color : str            Threshold line color.
#' @param threshold_line_type  : int            Threshold line type.
#' @param significant_markers  : data.frame     File name without csv extension
#'                                              generated by the function
#'                                              'extract_significant_markers'
#'                                              containing only the significant
#'                                              marker to highlight with
#'                                              'significant_color'. NULL value
#'                                              will highlight all markers
#'                                              according to 'significant_color'
#'                                              parameter.
#' @param gap_size             : float          Total size multiplier to define
#'                                              gap size between chromosomes.
#'
#' @returns ggplot2::ggplot object.
#' @export
#' @importFrom magrittr %>%
#' @examples
#' \dontrun{
#' plot_manhattan(data = data_with_threshold, significant_color = NULL)
#' }
plot_manhattan <- function (data,
                                           traits = NULL,
                                           models = NULL,
                                           chrom = NULL,
                                           chrom_color = c('#219ebc', '#8ecae6'),
                                           significant_color = '#fb8500',
                                           point_size = 1.5,
                                           point_alpha = NA,
                                           threshold_line_color = 'grey50',
                                           threshold_line_type = 2,
                                           significant_markers = NULL,
                                           gap_size = 0.01) {
  get_x <- function(map, gap_size = 0) {

    a <- tapply(map[,2], map[,1], max)
    n <- length(a)
    m <- tapply(map[,2], map[,1], length)
    b <- c(
      0,
      sapply(1:(n-1), function(k) {
        # Add gap size to current position based on number of chromosomes
        sum(a[1:k]) + (sum(a) * gap_size) * k
      })
    )

    x <- map[,2] + rep(b, times = m)
    return(x)
  }
  # Do not allow data without threshold unlike GWASpoly::manhattan.plot
  stopifnot(inherits(data, "GWASpoly.thresh"))

  if (is.null(traits)) {traits <- names(data@scores)}
  else {stopifnot(all(is.element(traits, names(data@scores))))}
  n.trait <- length(traits)
  all.models <- colnames(data@scores[[1]])
  if (is.null(models)) {
    models <- all.models
  } else {
    dom.models <- models[grep("dom", models, fixed = T)]
    models <- setdiff(models, dom.models)
    if (length(dom.models) > 0) {
      dom.models <- unlist(lapply(as.list(dom.models),
                                  function(x) {
                                    all.models[grep(x, all.models, fixed = T)]
                                  }))
    }
    models <- union(models, dom.models)
    stopifnot(all(is.element(models, all.models)))
  }
  plotme <- thresh.data <- NULL
  if (is.null(chrom)) {
    x <- get_x(data@map[, 2:3], gap_size = gap_size)
    ix <- 1:nrow(data@map)
  }
  else {
    stopifnot(chrom %in% levels(data@map$Chrom))
    ix <- which(as.character(data@map$Chrom) == chrom)
    x <- data@map$Position[ix]/1e+06
  }
  for (k in 1:n.trait) {
    scores <- as.data.frame(data@scores[[traits[k]]][ix, models])
    colnames(scores) <- models
    scores$x <- x

    # Add markers id for printable significant_markers match
    scores$Marker <- rownames(scores)

    scores$color <- factor(ifelse(as.integer(factor(data@map[ix, 2]))%%2 == 1, 1, 0))
    tmp <- tidyr::pivot_longer(data = scores,
                               cols = match(models, colnames(scores)),
                               names_to = "model",
                               values_to = "y",
                               values_drop_na = TRUE)
    tmp$trait <- traits[k]

    thresh.data <- dplyr::bind_rows(thresh.data, data.frame(y = max(data@threshold[traits[k], models]), trait = traits[k]))

    plotme <- dplyr::bind_rows(plotme, tmp)
  }
  plotme$trait <- factor(plotme$trait)
  plotme$model <- gsub(pattern = "-ref", replacement = "",
                       x = plotme$model)
  plotme$model <- gsub(pattern = "-alt", replacement = "",
                       x = plotme$model)
  plotme$model <- factor(plotme$model)

  # Find facet maximum value and add 1 LOD to increase Y limit
  facet_limits <- dplyr::bind_rows(plotme %>% dplyr::select(trait, y),
                                   thresh.data %>% dplyr::select(trait, y)) %>%
    dplyr::group_by(trait) %>%
    dplyr::summarise(y = max(y, na.rm = TRUE) + 1, .groups = 'drop')

  # Generate basic plot based on parameters
  p <- ggplot2::ggplot(data = plotme,
                       ggplot2::aes(x = .data$x, y = .data$y, colour = .data$color)) +
    ggplot2::ylab(expression(paste('-log'[10], '(p)'))) +
    ggplot2::guides(colour = 'none') +
    ggplot2::theme_bw() +
    ggplot2::theme(text = ggplot2::element_text(size = 15),
                   panel.grid = ggplot2::element_blank(),
                   axis.text.x = ggplot2::element_text(angle = 90,vjust = 0.5),
                   legend.position = 'none',
                   strip.background = ggplot2::element_blank()) +
    ggplot2::geom_point(size = point_size,
                        alpha = point_alpha) +
    ggplot2::scale_shape(solid = TRUE) +
    ggplot2::facet_wrap(~trait,
                        ncol = 1,
                        scales = 'free_y') +
    ggplot2::geom_blank(data = facet_limits,
                        ggplot2::aes(y = y),
                        inherit.aes = FALSE)

  # Look for significant markers highlight
  if (!is.null(significant_color)) {
    # Copy the original data for highlight and manipulation
    plotme_significant <- plotme %>%
      dplyr::left_join(thresh.data %>% dplyr::select(trait, thresh = y), by = 'trait')
    # Look for file name that contain a list of precise markers to highlight
    if (!is.null(significant_markers )){
      # Set show value to TRUE if markers are found in csv
      plotme_significant <- plotme_significant %>%
        dplyr::left_join(dplyr::select(significant_markers %>%
                                         dplyr::mutate(significant_show = TRUE),
                         trait, Marker, significant_show),
                  by = c("trait", "Marker")) %>%
        dplyr::mutate(significant_show = tidyr::replace_na(significant_show, FALSE))
    } else {
      # No file means highlight all significant markers
      plotme_significant <- plotme_significant %>%
        dplyr::mutate(significant_show = TRUE)
    }
    # Add highlighted markers over the current plot
    p <- p +
      ggplot2::geom_point(data = subset(plotme_significant, (y > thresh & significant_show)),
                          color = significant_color,
                          size = point_size,
                          alpha = point_alpha)
  }

  if (is.null(chrom)) {
    allchr <- unique(data@map[, 2])
    breaks <- (tapply(x, data@map[, 2], max) + tapply(x, data@map[, 2], min))/2
    # Plot each markers based on chromosome color
    p <- p +
      ggplot2::scale_x_continuous(name = 'Chromosome',
                                  breaks = breaks,
                                  labels = allchr,
                                  expand = ggplot2::expansion(mult = gap_size)) +
      ggplot2::scale_colour_manual(values = chrom_color)
  } else {
    # Plot each markers based on odd or even chromosome index
    p <- p +
      ggplot2::scale_x_continuous(name = 'Position (Mb)') +
      ggplot2::scale_colour_manual(values = chrom_color[(which(unique(as.character(data@map$Chrom)) == chrom) %% 2) + 1])
  }
  p <- p +
    ggplot2::geom_hline(data = thresh.data,
                        mapping = ggplot2::aes(yintercept = .data$y),
                        linetype = threshold_line_type,
                        colour = threshold_line_color)
  return(p)
}
