#' Save beautified Manhattan plot with the right ratio
#'
#' @param gwas_plot : ggplot  ggplot2::ggplot object generated by
#'                            'GWASpoly_beautifier::plot_manhattan'.
#' @param file_name : str     File name to save Manhattan plot.
#'
#' @export
#' @examples
#' save_manhattan(gwas_plot = p, file_name = "vine_maturity_manhattan.png")
save_manhattan <- function(gwas_plot, file_name){
  # Allow only data from GWASpoly::set.threshold(...) command
  stopifnot(inherits(gwas_plot, 'ggplot'))
  # Get facets count to define document height
  supplementary_panel_count <- length(unique(ggplot2::ggplot_build(gwas_plot)$layout$layout$PANEL))-1
  # Output file based on file_type
  ggplot2::ggsave(filename = file_name,
                  plot = gwas_plot,
                  width = 11.25,
                  height = 2.25 + (supplementary_panel_count) * 1.75,
                  units = "in")
}
